### ISSUE TITLE
Global variable declarations in QuickButton.gui_script

### ISSUE THREAD

**Issue by britzl** [GamingBud/QuickButton#3]
There's a couple of global variables declared in the script. I would suggest that `gui_buttons` and `gui_button_owners` are declared as script variables in init()

	function init(self)
		msg.post(".", "acquire_input_focus")
		self.gui_buttons = {}
		self.gui_button_owners = {}
	end

And that you pass `self` as the first argument to `Create_Button`, `Click_Button` and `Highlight_Button`

**Comment by GamingBud** [comment]
I left them global so that they could be used by an asset users' scripts to find and or delete the nodes. As you pointed out though, I overlooked the fact that GUI instances cannot be deleted from a different GUI script.

I can see why though. There is a possibility that the user could create the same named variable unknowingly for another purpose and reek havoc until they figured it out.

Fixed in Version 0.2.
